### ISSUE TITLE
crash on reloading into the StarCoreMTworld due to another mod also watching the network(?)

### ISSUE THREAD

**Issue by InvalidArgument3** [ari-steas/ModNetworkProfiler#1]
doesn't happen in a vanilla one

```
2024-09-26 05:08:40.409 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at SC.SUGMA.Log.Exception(Exception ex, Type callingType, String prefix)
   at SC.SUGMA.HeartNetworking.HeartNetwork.ReceivedPacket(UInt16 channelId, Byte[] serialized, UInt64 senderSteamId, Boolean isSenderServer)
   at System.Action`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageClientReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
2024-09-26 05:08:40.409 - Thread:   1 ->  Packet processing error, disconnecting VRage.Network.Endpoint
2024-09-26 05:08:40.410 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SC.SUGMA.Log.Exception(Exception ex, Type callingType, String prefix)
   at SC.SUGMA.HeartNetworking.HeartNetwork.ReceivedPacket(UInt16 channelId, Byte[] serialized, UInt64 senderSteamId, Boolean isSenderServer)
   at System.Action`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageClientReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Sandbox.Engine.Networking.MyNetworkReader.Process()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-09-26 05:08:40.413 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at SC.SUGMA.Log.Exception(Exception ex, Type callingType, String prefix)
   at SC.SUGMA.HeartNetworking.HeartNetwork.ReceivedPacket(UInt16 channelId, Byte[] serialized, UInt64 senderSteamId, Boolean isSenderServer)
   at System.Action`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageClientReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Sandbox.Engine.Networking.MyNetworkReader.Process()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-09-26 05:08:40.413 - Thread:   1 ->  Showing message
2024-09-26 05:08:40.413 - Thread:   1 ->  MyInitializer.OnCrash
2024-09-26 05:08:40.413 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at SC.SUGMA.Log.Exception(Exception ex, Type callingType, String prefix)
   at SC.SUGMA.HeartNetworking.HeartNetwork.ReceivedPacket(UInt16 channelId, Byte[] serialized, UInt64 senderSteamId, Boolean isSenderServer)
   at System.Action`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageClientReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Sandbox.Engine.Networking.MyNetworkReader.Process()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

**Comment by InvalidArgument3** [comment]
this PR attempts to sprayfoam that but it just moves on to the logger of sugma/sharetrack itself. something about them the plugin interferes with
https://github.com/StarCoreSE/SCModRepository/pull/1691

```
2024-09-28 23:26:20.231 - Thread:   1 ->  var exception = System.Exception: Digi.Log accessed after it was unloaded!
   at StarCore.ShareTrack.Log.EnsureHandlerCreated()
   at StarCore.ShareTrack.Log.Error(Exception exception, String printText, Int32 printTimeMs)
   at StarCore.ShareTrack.HeartNetworking.HeartNetwork.ReceivedPacket(UInt16 channelId, Byte[] serialized, UInt64 senderSteamId, Boolean isSenderServer)
   at System.Action`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageClientReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Sandbox.Engine.Networking.MyNetworkReader.Process()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

**Comment by InvalidArgument3** [comment]
incompat with build and repair's logger (the deltaV fork)

```
2024-11-23 19:27:30.251 - Thread:   1 ->  NanobotBuildAndRepairSystem Error while logging message='BuildAndRepairSystemMod: SyncBlockStateReceived for unknown system EntityId=75040146715464541'
Logger error: The process cannot access the file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Storage\3366634953.sbm_SKO-Nanobot-BuildAndRepair-System\NanobotBuildAndRepairSystem.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at VRage.FileSystem.MyFileSystem.OpenWrite(String path, FileMode mode)
   at Sandbox.ModAPI.MyAPIUtilities.VRage.Game.ModAPI.IMyUtilities.WriteFileInLocalStorage(String file, Type callingType)
   at SKONanobotBuildAndRepairSystem.Logging.Write(String msg)
2024-11-23 19:27:30.278 - Thread:   1 ->  NanobotBuildAndRepairSystem Error while logging message='BuildAndRepairSystemMod: SyncBlockStateReceived for unknown system EntityId=106900557883522208'
Logger error: The process cannot access the file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Storage\3366634953.sbm_SKO-Nanobot-BuildAndRepair-System\NanobotBuildAndRepairSystem.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at VRage.FileSystem.MyFileSystem.OpenWrite(String path, FileMode mode)
   at Sandbox.ModAPI.MyAPIUtilities.VRage.Game.ModAPI.IMyUtilities.WriteFileInLocalStorage(String file, Type callingType)
   at SKONanobotBuildAndRepairSystem.Logging.Write(String msg)
```

**Comment by InvalidArgument3** [comment]
no longer happens since newest commits
